Initialized dataset with  64000  samples.
Epoch 0, Train Loss: 516.79, Val Loss: 412.77, Test Loss: 408.79
Traceback (most recent call last):
  File "vae_generate.py", line 34, in <module>
    plt.imshow(img, cmap='gray')
NameError: name 'img' is not defined
