Initialized dataset with  64000  samples.
Epoch 0, Train Loss: 523.91, Val Loss: 413.34, Test Loss: 415.94
Using TensorFlow backend.
test
336
[1.         1.         1.0000001  1.0000001  1.         0.99999994
 0.99999994 1.0000001  1.0000001 ]
336
[1.         0.99999994 1.         0.99999994 0.99999994 0.99999994
 0.99999994 1.         0.99999994]
336
[1.0000001  1.         1.         1.         0.99999994 1.
 1.         1.         1.        ]
336
[0.99999994 0.9999999  1.0000001  1.         1.         0.99999994
 1.0000001  0.99999994 1.        ]
336
[0.99999994 1.0000001  1.         1.         0.99999994 1.
 0.99999994 1.0000001  1.        ]
336
[1.0000001  0.99999994 1.         1.0000001  0.99999994 1.
 1.         0.99999994 1.0000001 ]
336
[0.99999994 1.         1.0000001  0.99999994 1.0000001  1.
 1.         0.99999994 0.99999994]
336
[0.99999994 0.99999994 1.0000001  1.         1.         1.
 1.0000001  0.99999994 1.        ]
336
[1.         1.0000001  0.99999994 1.         1.0000001  0.99999994
 1.         1.0000001  1.        ]
Traceback (most recent call last):
  File "vae_generate.py", line 34, in <module>
    render(img)
NameError: name 'render' is not defined
